import Head from 'next/head'
import {GraphQLClient,  gql} from  'graphql-request';
import { BlogCard } from '@/components/BlogCard';

const graphcms = new GraphQLClient(
  'https://api-ap-south-1.hygraph.com/v2/clfxvovhh68gm01t7glrhfsv6/master'
);

const QUERY =  gql`
{
  posts {
    id,
    title,
    datePublished,
    slug,
    content {
      html,
    }
    coverPhoto {
      url
    }
  }
}
`

export async function getStaticProps() {
  const {posts} = await graphcms.request(QUERY);
  console.log(posts.id);
  return {
    props: {
      posts: {
        posts
      },
      revalidate: 10,
    }
  }
}
export default function Home({posts}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {posts.array.map((post) => {
          <BlogCard 
          title={post.title} 
          coverPhoto={post.coverPhoto}
          key={post.id}
          datePublished={datePublished}
          slug={post.slug}
        />
        })}
      </main>
      
    </>
  )
}
